[build]
  command = "CI= npm run build && cd functions/node-fetch && npm install"
  functions = "functions"
  publish = "build"
[[redirects]]
  from = "/"
  to = "/provinces"
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"